name: Build and upload to Maestro Cloud (Flutter)
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # android:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Set up Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       channel: "stable"
  #   - name: Build APK
  #     run: flutter build apk --debug
  #   - name: Upload to Maestro Cloud
  #     uses: mobile-dev-inc/action-maestro-cloud@v1
  #     with:
  #       api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
  #       app-file: build/app/outputs/flutter-apk/app-debug.apk
  #       env: |
  #           APP_ID=${{ secrets.APP_ID }}

  ios:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
    - name: Build iOS
      run: flutter build ios --debug --simulator
    - name: Upload to Maestro Cloud
      uses: mobile-dev-inc/action-maestro-cloud@v1
      with:
        api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
        app-file: build/ios/iphonesimulator/Runner.app
        env: |
            APP_ID=${{ secrets.APP_ID }}
        
